### ISSUE TITLE
Build Failed on IOS

### ISSUE THREAD

**Issue by yuzurihaaa** [FlutterRocks/separating_build_environments#1]
```
Launching lib/main_dev.dart on iPhone X in debug mode...
Running Xcode clean...
Starting Xcode build...
Xcode build done
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The path lib/main.dart does not exist
    Command /bin/sh failed with exit code 255
Could not build the application for the simulator.
Error launching application on iPhone X.
```

I get this when I clone and tried to run the project, I did the editConfiguration based on https://flutter.rocks/2018/03/02/separating-build-environments-part-one/

**Comment by roughike** [comment]
Hi!

I was able to reproduce the same error when cloning the project.

A temporary workaround I came up with is the following:

1. `cd <your Flutter project root>`
2. `flutter create .` - (yes, with the `.` at the end)
3. now you should be able to do `flutter run -t lib/main_dev.dart` properly, or use the Run Configurations from IntelliJ IDEA / Android Studio.

I'll look into this more, but I'm currently busy. Let me know if that helps!
